### ISSUE TITLE
Startup Issue

### ISSUE THREAD

**Issue by GrimneLothos** [TEALSK12/teals-minecraft#18]
[10:35:34] [main/INFO] [GradleStart]: Extra: []
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraftforge.gradle.GradleStartCommon.searchCoremods(GradleStartCommon.java:222)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:105)
	at GradleStart.main(GradleStart.java:47)

**Comment by GrimneLothos** [comment]
ok so the solution is to download the old jre and point the project at it.
